### ISSUE TITLE
[bug] Setting AllowedIPs results in invalid configuration

### ISSUE THREAD

**Issue by gaby** [cmusatyalab/wireguard-tools#12]
@jaharkes  Found an interesting bug that's not covered in the unit-tests. Updating the AllowedIPs results in a config file with 2 entries for "AllowedIPs". Something is not right with the conversion between a list and the string fields.

```python
from wireguard_tools import WireguardConfig

config = None

with open("wg0.conf") as fh:
    config = WireguardConfig.from_wgconfig(fh)

for _, peer in config.peers.items():
    peer.allowed_ips = [IPv4Interface("192.168.0.0/16"), IPv4Interface("10.168.0.0/16")]

print(config.to_wgconfig(wgquick_format=True))
```

The printed config will have 2 entries for `AllowedIPs`:

```conf
AllowedIPs = "192.168.0.0/16"
AllowedIPs = "10.168.0.0/16"
```

Instead it should be:

```conf
AllowedIPs = "192.168.0.0/16,10.168.0.0/16"
```

**Comment by jaharkes** [comment]
Weirdly enough, that is valid in the Wireguard config file and part of the reason why we can't use off-the-shelf configparser.ConfigParser to read the config files.

Since both forms are acceptable, I found it easier to break down the list of addresses into the multiple AllowedIPs form instead of adding commas and spaces between entries, but not at the end, and possibly dealing with line wrapping long lines, etc.

https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8

> The Peer sections may contain the following fields:
> ...
> -  AllowedIPs -  a comma-separated list of IP (v4 or v6) addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed. The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses. *May be specified multiple times.*

According to the wg-quick manual page, the two different forms (comma separated and specifying multiple times) are valid for the Address and DNS fields as well. It also shows an example with two Address fields in the Interface section.

https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8

**Comment by gaby** [comment]
@jaharkes Thanks! I will keep debugging for some reason when I use this the interface fails to come up.
